// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Rohan Kumar Thakur",
            "email": "rohandeveloper106@gmail.com"
        },
        "license": {
            "name": "GNU GENERAL PUBLIC LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cart/add-product": {
            "post": {
                "summary": "Add a product to user's cart",
                "responses": {}
            }
        },
        "/cart/delete-product": {
            "post": {
                "summary": "Delete a product from user's cart",
                "responses": {}
            }
        },
        "/cart/remove-product": {
            "post": {
                "summary": "Remove a product from user's cart",
                "responses": {}
            }
        },
        "/order/order-details": {
            "get": {
                "summary": "It sends list of items included in an order",
                "responses": {}
            }
        },
        "/order/read-order": {
            "get": {
                "summary": "get list of orders in paginated way",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "e-commerce api",
	Description:      "This is a Go application having JWT authentication, Unit tests,etc using postgresql as database",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
