version: '3.7'
services:
  node:
    image: "node:18-alpine"
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    user: "node"
    working_dir: /home/rohan/Code/projects/e-commerce/frontend
    volumes:
      - ./:/home/rohan/Code/projects/e-commerce/frontend
    