// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: discount.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getDiscount = `-- name: GetDiscount :one
select discount_id from public.discounts where lower(code) = lower($1) and status = 'active' and expired_on > current_timestamp
`

func (q *Queries) GetDiscount(ctx context.Context, lower string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getDiscount, lower)
	var discount_id uuid.UUID
	err := row.Scan(&discount_id)
	return discount_id, err
}
