// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: discount.sql

package db

import (
	"context"
)

const getDiscount = `-- name: GetDiscount :one
select code from public.discounts where lower(code) = lower($1) and status = 'active' and expired_on > current_timestamp
`

func (q *Queries) GetDiscount(ctx context.Context, lower string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDiscount, lower)
	var code string
	err := row.Scan(&code)
	return code, err
}
