development:
  dialect: postgres
  url: "postgresql://root:root@127.0.0.1:5432/khushidb?sslmode=disable"
  pool: 5

production:
  url: "postgresql://root:root@127.0.0.1:5432/khushidb?sslmode=disable"
