development:
  dialect: postgres
  url: "postgresql://postgres:root@127.0.0.1:5432/e_commerce?sslmode=disable"
  pool: 5

production:
  url: "postgresql://postgres:root@127.0.0.1:5432/e_commerce?sslmode=disable"
