// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddDiscount(ctx context.Context, arg AddDiscountParams) error
	CheckCartDetail(ctx context.Context, arg CheckCartDetailParams) (int32, error)
	CountCartId(ctx context.Context, userID uuid.NullUUID) (int64, error)
	CountUser(ctx context.Context, lower string) (int64, error)
	CreateCart(ctx context.Context, userID uuid.NullUUID) error
	CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error)
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error
	FindUserOne(ctx context.Context, lower string) (FindUserOneRow, error)
	GetCartDetails(ctx context.Context, userID uuid.NullUUID) (GetCartDetailsRow, error)
	GetCartID(ctx context.Context, userID uuid.NullUUID) (uuid.UUID, error)
	GetCartItems(ctx context.Context, cartID uuid.NullUUID) ([]GetCartItemsRow, error)
	GetDiscount(ctx context.Context, lower string) (GetDiscountRow, error)
	GetDiscountCount(ctx context.Context, arg GetDiscountCountParams) (int64, error)
	GetProductImages(ctx context.Context, productID uuid.NullUUID) ([]GetProductImagesRow, error)
	InsertCartItem(ctx context.Context, arg InsertCartItemParams) error
	ReadAllCategories(ctx context.Context) ([]ReadAllCategoriesRow, error)
	ReadAllProducts(ctx context.Context, arg ReadAllProductsParams) ([]ReadAllProductsRow, error)
	ReadCartItemQuantity(ctx context.Context, arg ReadCartItemQuantityParams) (sql.NullInt32, error)
	ReadCategory(ctx context.Context, productID uuid.UUID) (uuid.UUID, error)
	ReadCategoryItems(ctx context.Context, arg ReadCategoryItemsParams) ([]ReadCategoryItemsRow, error)
	ReadCategoryProduct(ctx context.Context, categoryID uuid.UUID) ([]VProduct, error)
	ReadNewProducts(ctx context.Context, arg ReadNewProductsParams) ([]ReadNewProductsRow, error)
	ReadOneCategory(ctx context.Context, categoryID uuid.UUID) (ReadOneCategoryRow, error)
	ReadOneProduct(ctx context.Context, productID uuid.UUID) (ReadOneProductRow, error)
	ReadProductQuantity(ctx context.Context, productID uuid.UUID) (sql.NullInt32, error)
	ReadSimilarItems(ctx context.Context, arg ReadSimilarItemsParams) ([]ReadSimilarItemsRow, error)
	ReadUser(ctx context.Context, userID uuid.UUID) (User, error)
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error
	RemoveDiscount(ctx context.Context, arg RemoveDiscountParams) error
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error
}

var _ Querier = (*Queries)(nil)
