version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=khushi
    ports:
      - 5432:5432

  # api:
  #   image: "golang:1.21-alpine"
  #   command: sh -c "go install -v github.com/cosmtrek/air@latest && go mod tidy && air"
  #   ports:
  #     - 8080:8080
  #   working_dir: /home/rohan/Code/projects/e-commerce/api
  #   volumes:
  #     - ./:/home/rohan/Code/projects/e-commerce/api
  #   environment:
  #     - DB_SOURCE=postgresql://root:root@postgres:5432/khushi?sslmode=disable
  #   depends_on:
  #     - postgres

volumes:
  db:
